# Generated by Django 5.1.4 on 2025-02-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawBloco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField()),
                ("ticket_info", models.CharField(blank=True, max_length=50, null=True)),
                ("ticket_url", models.URLField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("address_gmaps_url", models.URLField(blank=True, null=True)),
                ("event_page_url", models.URLField(blank=True, null=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("event_day", models.CharField(blank=True, max_length=20, null=True)),
                ("event_time", models.TimeField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Bloco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField()),
                ("ticket_info", models.CharField(blank=True, max_length=50, null=True)),
                ("ticket_url", models.URLField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("address_gmaps_url", models.URLField(blank=True, null=True)),
                ("event_page_url", models.URLField(blank=True, null=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("event_day", models.CharField(blank=True, max_length=20, null=True)),
                ("event_time", models.TimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaned_data",
                        to="carnaval_map.rawbloco",
                    ),
                ),
            ],
        ),
    ]
