# Generated by Django 5.1.4 on 2025-02-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carnaval_map", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloco",
            name="event_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="rawbloco",
            name="event_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
